//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karkas_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mihailova_demo2Entities : DbContext
    {
        private static Mihailova_demo2Entities context;
        public Mihailova_demo2Entities()            
            : base("name=Mihailova_demo2Entities")
        {
            
        }
    
        public static Mihailova_demo2Entities getContext()
        {
            if (context == null)
            {
                context = new Mihailova_demo2Entities();
            }
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agent { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_agent> product_agent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
