//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karkas_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_agent = new HashSet<product_agent>();
        }
    
        public int ID { get; set; }
        public string Name_product { get; set; }
        public string Type_product { get; set; }
        public Nullable<double> Artikul { get; set; }
        public Nullable<double> Kol_chel { get; set; }
        public Nullable<double> Number_cexa { get; set; }
        public Nullable<double> min_cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_agent> product_agent { get; set; }
    }
}
